# [NumPy](https://numpy.org/)

NumPy is the foundational package for mathematical computing in Python.
- Supports fast and efficient multidimensional arrays (ndarray)
- Executes element-wise computations and mathematical calculations
- Performs linear algebraic operations, Fourier transforms, and random number generation
- Tools for reading/writing array based datasets to disk
- Efficient way of storing and manipulating data
- Tools for integrating language codes (C, C++)

Numerical Python (NumPy) supports multidimensional arrays over which you can easily apply mathematical operations.

In [1]:
distance = [10,15,17,26]
time = [.30,.47,.55,1.20]

To performe mathematial operations, first need to import the [NumPy](https://numpy.org/) library

In [2]:
import numpy as np

In [3]:
np_distance = np.array(distance)   #Converting the "distance,time" list to NumPy arrays
np_time = np.array(time)
speed = np_distance/np_time    #Mathematical function applied over the entire “distance” and “time” arrays

In [4]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

### Properties of ndarray

- Collection of values
- Add, remove, change
- Single type (homogeneous)
- Multidimensional
- Mathematical function support
- Fast and efficient

### Purpose of ndarray
The ndarray in Python is used as the primary container to exchange data between algorithms.

###### Classes and Attributes of ndarray: .ndim
The array **np_city** is one-dimensional, while the array **np_city_with_state** is two-dimensional.

In [5]:
np_city = np.array(['NYC','LA','Miami','Houston'])

In [6]:
np_city.ndim

1

In [7]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])

In [8]:
np_city_with_state.ndim

2

##### Classes and Attributes of ndarray: .shape
Numpy’s array class is **ndarray**, also referred to as **numpy.ndarray**.

In [9]:
#The shape tuple of both the arrays indicate their size along each dimension.

In [10]:
np_city = np.array(['NYC','LA','Miami','Houston'])

In [11]:
np_city_with_state = np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])

In [12]:
np_city.shape

(4,)

In [13]:
np_city_with_state.shape

(2, 4)

##### Classes and Attributes of ndarray: .size
Numpy’s array class is **ndarray**, also referred to as **numpy.ndarray**.

In [14]:
np_city.size

4

In [15]:
np_city_with_state.size

8

##### Classes and Attributes of ndarray: .dtype
Numpy’s array class is **ndarray**, also referred to as **numpy.ndarray**.

In [16]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [17]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [18]:
np_city_with_state.dtype

dtype('<U7')

## Basic Operations

NumPy uses the indices of the elements in each array to carry out basic operations. In this case, where we are looking at a dataset of four cyclists during two trials, vector addition of the arrays gives the required output.

### Example

In [19]:
first_trial_cyclist = [10,15,17,26]

In [20]:
second_trial_cyclist = [12,11,21,24]

In [21]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [22]:
np_second_trial_cyclist = np.array(second_trial_cyclist)

In [23]:
#Total Distance

np_first_trial_cyclist + np_second_trial_cyclist

array([22, 26, 38, 50])

### Accessing Array Elements: Indexing
can access an entire row of an array by referencing its axis index.

In [24]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [25]:
first_trial = cyclist_trials[0]

In [26]:
first_trial

array([10, 15, 17, 26])

In [27]:
second_trial = cyclist_trials[1]

In [28]:
second_trial

array([12, 11, 21, 24])

### Accessing Array Elements: Indexing
can refer the indices of the elements in an array to access them. You can also select a particular index of more than one axis at a time.

In [29]:
first_cyclist_firstTrial = cyclist_trials[0][0]

In [30]:
first_cyclist_firstTrial

10

In [31]:
first_cyclist_all_trials = cyclist_trials[:,0]

#First cyclist: all trial data (Use : to select all the rows of an array)

In [32]:
first_cyclist_all_trials

array([10, 12])

### Accessing Array Elements: Slicing
Use the slicing method to access a range of values within an array.

In [33]:
cyclist_trials.shape

(2, 4)

In [34]:
two_cyclist_trial_data = cyclist_trials[:,1:3]

#Slicing the array data [ : , 1 : 3]
#where 1 is inclusive but 3 is not

In [35]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

### Accessing Array Elements: Iteration
Use the iteration method to go through each data element present in the dataset.

In [36]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [37]:
two_cyclist_trial_data = cyclist_trials[:,1:3]

In [38]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [39]:
for iterate_cyclist_trials_data in cyclist_trials:
    print (iterate_cyclist_trial_data)

#Iterate with for loop through entire dataset

NameError: name 'iterate_cyclist_trial_data' is not defined

In [40]:
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)
    
#Iterate with for loop through the two cyclist datasets

[15 17]
[11 21]


### Indexing with Boolean Arrays
Here, the original dataset contains test scores of two students. You can use a Boolean array to choose only the scores that are above a given value.

In [41]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [42]:
passing_score = test_scores > 60   #Setting the passing score

In [43]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [44]:
test_scores[passing_score]  #Send passing score as an argument to test scores object

array([83, 71, 63, 68, 81])

## Copy and Views
When working with arrays, data is copied into new arrays only in some cases.

In this method, a variable is directly assigned the value of another variable. No new copy is made.

In [45]:
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','Staten Iceland','Queens'])

In [46]:
NYC_Borough        #Original dataset

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Queens'],
      dtype='<U14')

In [47]:
Boroughs_in_NYC = NYC_Borough

In [48]:
Boroughs_in_NYC      #Assigned dataset

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Queens'],
      dtype='<U14')

In [49]:
Boroughs_in_NYC is NYC_Borough     #Shows both objects are the same

True

In [50]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Queens'],
      dtype='<U14')

In [51]:
View_of_Boroughs_in_NYC = Boroughs_in_NYC.view()

In [52]:
len(View_of_Boroughs_in_NYC)

5

In [53]:
View_of_Boroughs_in_NYC[4] = 'Central Park'     #Change value in view object

In [54]:
View_of_Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Central Park'],
      dtype='<U14')

In [55]:
Boroughs_in_NYC          #Original dataset changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Central Park'],
      dtype='<U14')

Copy is also called **deep copy** because it entirely copies the original dataset. Any change in the copy will not affect the original dataset.

In [62]:
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','Staten Iceland','Queens'])

In [63]:
Copy_of_NYC_Borough = NYC_Borough.copy()

In [64]:
Copy_of_NYC_Borough is NYC_Borough    #Shows copy and original object are different

False

In [65]:
Copy_of_NYC_Borough.base is NYC_Borough    #Shows copy object data is not owned by the original dataset

False

In [66]:
Copy_of_NYC_Borough[4] = 'Central Park'

In [67]:
NYC_Borough     #Original dataset retained

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Queens'],
      dtype='<U14')

In [68]:
Copy_of_NYC_Borough     #Copy object changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Iceland', 'Central Park'],
      dtype='<U14')

## Universal Functions (ufunc)
NumPy provides useful mathematical functions called Universal Functions. These functions operate element-wise on an array, producing another array as output.
- sqrt
- cos
- exp
- floor

#### Example

In [69]:
np_sqrt = np.sqrt([2,4,9,16])   #Numbers for which square root will be calculated

In [70]:
np_sqrt     #Square root values

array([1.41421356, 2.        , 3.        , 4.        ])

In [71]:
from numpy import pi    #Import pi

In [72]:
np.cos(0)

1.0

In [73]:
np.sin(pi/2)

1.0

In [74]:
np.cos(pi)

-1.0

In [75]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])   #Return the floor of the input element wise

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [76]:
np.exp([0,1,5])    #Exponential functions for complex mathematical calculations

array([  1.        ,   2.71828183, 148.4131591 ])

## Shape Manipulation
The shape of an array can be changed according to the requirement using the NumPy library functions.
- Flatten
- Resize
- Reshape
- Stack
- Split

#### Example

In [77]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [78]:
new_cyclist_trials.ravel()   #Flattens the dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [79]:
new_cyclist_trials.reshape(3,4)   #Changes or reshapes the dataset to 3 rows and 4 columns

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [80]:
new_cyclist_trials.resize(2,6)   #Resizes again to 2 rows and 6 columns

In [81]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [83]:
np.hsplit(new_cyclist_trials,2)     #Splits the array into two

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [84]:
new_cyclist_1 = np.array([10,15,17,26,13,19])

In [85]:
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [86]:
np.hstack((new_cyclist_1,new_cyclist_2))    #Stacks the arrays together

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

## Broadcasting
NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array.

In [87]:
import numpy as np

In [88]:
#create two arrays of the same shape

array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [89]:
#Multiply arrays

array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [90]:
#Create a variable with a scalar value

scalar_c = .3

In [92]:
#Multiply with 1D array with a scalar value

array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

If the shape doesn’t match with array_a, numpy doesn’t have to create copies of scalar value. Instead, broadcast scalar value over the entire array to find the product.

#### Broadcasting: Constraints
Though broadcasting can help carry out mathematical operations between different-shaped arrays, they are subject to certain constraints

In [93]:
import numpy as np

In [94]:
#create two arrays of the same shape

array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [95]:
#Multiply arrays

array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [98]:
#Create array of a different shape

array_d = np.array([4,3])

In [99]:
array_a * array_d

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Let’s look at an example to see how broadcasting works to calculate the number of working hours of a worker per day in a certain week.

In [100]:
np_week_one = np.array([105,135,195,120,165])  #Week one earnings
np_week_two = np.array([123,156,230,200,147])  #Week two earnings

In [101]:
total_earning = np_week_one + np_week_two

In [102]:
total_earning

array([228, 291, 425, 320, 312])

In [103]:
np_week_one_hrs = np_week_one/15   # Calculate week one hours, when Hourly wage is 15

In [104]:
np_week_one_hrs

array([ 7.,  9., 13.,  8., 11.])

### Linear Algebra: Transpose
NumPy can carry out linear algebraic functions as well. The **transpose()** function can help you interchange rows as columns, and vice-versa.

In [106]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [107]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

### Linear Algebra: Inverse and Trace Functions
Using NumPy, you can also find the inverse of an array and add its diagonal data elements. **np.linalg.inv()** | **np.trace()**

In [108]:
inverse_array = np.array([[10,20],[15,25]])

In [109]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

* Can be applied **only** on a square matrix

In [110]:
trace_array = np.array([[10,20],[22,31]])

In [111]:
np.trace(trace_array)      #Sum of diagonal elements 10 and 31

41