# [SciPy](https://www.scipy.org/)
SciPy has built-in packages that help in handling the scientific domains.
- Built-in mathematical libraries and functions
- High-level commands for data manipulation and visualization
- Efficient and fast data processing
- Integrates well with multiple systems and environments
- Large collection of sub-packages for different scientific domains
- Simplifies scientific application development

****

Some widely used **SciPy Packages**
- Integration
- IO
- Linear Algebra
- Optimize
- Statistics
- Weave packages

****

### SciPy Sub-Package
- **cluster** (Clustering algorithms)
- **ndimage** (N-dimensional image processing)
- **constants** (Physical and mathematical constant)
- **odr** (Orthogonal distance regression)
- **fftpack** (Fast Fourier Transform routines)
- **optimize** (Optimization and root-finding routines)
- **integrate** (Integration and ordinary differential equation solvers)
- **signal** (Signal processing)
- **Spatial** (Spatial data structures and algorithms)
- **sparse** (Sparse matrices and associated routines)
- **interpolate** (Interpolation and smoothing splines)
- **weave** (C/C++ integration)
- **IO** (Input and Output)
- **stats** (Statistical distributions and functions)
- **linalg** (Linear algebra)
- **special** (Special functions)

****

#### SciPy Sub-Package: Integration
This example shows how to perform quad integration.

In [1]:
#Import quad from integrate sub-package

from scipy.integrate import quad

In [2]:
#Define function for integration of x

def integrateFunction(x):
    return x

In [3]:
#Perform quad integration for function of x for limit 0 to 1

quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [6]:
#Define function for ax + b

def integrateFn(x,a,b):
    return x*a+b

In [7]:
#Declare value of a and b

a=3
b=2

In [8]:
#Perform quad integration and pass functions and arguments

quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

This example shows you how to perform multiple integration.

In [9]:
#Import integrate package sub-package

import scipy.integrate as integrate

In [10]:
#Define function for x + y
#Perform multiple integration using the lambda built-in function

def f(x,y):
    return x+y
integrate.dblquad(f,0,1,lambda x:0,lambda x:2)

(3.0, 4.436070580899685e-14)

### SciPy Sub-Package: Optimization
Optimization is a process to improve performance of a system mathematically by fine-tuning the process parameters.

SciPy provides several optimization algorithms, such as bfgs, Nelder-Mead simplex, Newton Conjugate Gradient, COBYLA, or SLSQP.

In [11]:
#Import numpy and optimize from SciPy

import numpy as np
from scipy import optimize

In [12]:
#Define function for X^2 + 5 sin x

def f(x):
    return x**2 + 5*np.sin(x)

In [14]:
# Perform optimize minimize function using bfgs method and options

minimaValue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [16]:
#Perform optimize minimize function using bfgs method and without options

minimaValueWithoutOpt = optimize.minimize(f,x0=2,method='bfgs')

In [17]:
minimaValueWithoutOpt

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

-

In [18]:
#Define function for X + 3.5 Cos x

import numpy as np
from scipy.optimize import root

def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [19]:
#Pass x value in argument for root

rootValue = root(rootfunc, 0.3)

In [20]:
rootValue

#Function value and array values

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

### SciPy Sub-Package: Linear Algebra
SciPy provides rapid linear algebra capabilities and contains advanced algebraic functions.

#### Inverse of matrix
This function is used to compute the inverse of the given matrix.

In [1]:
#Import linalg

import numpy as np
from scipy import linalg

In [2]:
#Define a numpy matrix or array

matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [3]:
type(matrix)

numpy.ndarray

In [4]:
#Use inv function to inverse the matrix

linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

#### Finding Determinant
With this function you can compute the value of the determinant for the given matrix.

In [5]:
#Use det function to find the determinant value of the matrix

linalg.det(matrix)

58.0

#### Solve Linear systems

**Linear equations**:

2x + 3 y + z = 21

-x + 5y + 4z = 9

3x + 2y + 9z = 6

In [6]:
#Define a numpy matrix or array

numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [7]:
numArrValue = np.array([21,9,6])

In [8]:
#Use solve method

linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

#### Single Value Decomposition (SVD)

In [9]:
#Define matrix

numSvdArr = np.array([[3,5,1],[9,5,7]])

In [10]:
#Find shape of ndarray which is 2X3 matrix

numSvdArr.shape

(2, 3)

In [11]:
#Use svd function

linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

### SciPy Sub-Package: Statistics

#### Perform Normal Distribution

In [13]:
#Import norm for normal distribution

from scipy.stats import norm

In [14]:
norm.rvs(loc=0, scale=1, size=10)   #rvs for Random variables

array([-0.12191519, -0.31497165, -0.87501177, -0.0922033 ,  0.26173803,
       -1.15893338, -0.36514345, -0.20933872,  0.02434207, -1.20970977])

In [15]:
norm.cdf(5, loc=1, scale=2)   #cdf for Cumulative Distribution Function

0.9772498680518208

In [16]:
norm.pdf(9, loc=0,scale=1)    #pdf for Probability Density Function for random distribution

1.0279773571668917e-18

**loc** and **scale** are used to adjust the location and scale of the data distribution.

### SciPy Sub-Package: Weave
The weave package provides ways to modify and extend any supported extension libraries.